/**
 * This file contains shared dropdown options used across the application
 */
export const COUNTRY_CODES = [
  { id: "AF", label: "Афганистан" },
  { id: "AX", label: "Оландски острови" },
  { id: "AL", label: "Албания" },
  { id: "DZ", label: "Алжир" },
  { id: "AS", label: "Американска Самоа" },
  { id: "AD", label: "Андора" },
  { id: "AO", label: "Ангола" },
  { id: "AI", label: "Ангуила" },
  { id: "AQ", label: "Антарктида" },
  { id: "AG", label: "Антигуа и Барбуда" },
  { id: "AR", label: "Аржентина" },
  { id: "AM", label: "Армения" },
  { id: "AW", label: "Аруба" },
  { id: "AU", label: "Австралия" },
  { id: "AT", label: "Австрия" },
  { id: "AZ", label: "Азербайджан" },
  { id: "BS", label: "Бахами" },
  { id: "BH", label: "Бахрейн" },
  { id: "BD", label: "Бангладеш" },
  { id: "BB", label: "Барбадос" },
  { id: "BY", label: "Беларус" },
  { id: "BE", label: "Белгия" },
  { id: "BZ", label: "Белиз" },
  { id: "BJ", label: "Бенин" },
  { id: "BM", label: "Бермуда" },
  { id: "BT", label: "Бутан" },
  { id: "BO", label: "Боливия" },
  { id: "BQ", label: "Бонер, Синт Еустатиус и Саба" },
  { id: "BA", label: "Босна и Херцеговина" },
  { id: "BW", label: "Ботсвана" },
  { id: "BV", label: "Остров Буве" },
  { id: "BR", label: "Бразилия" },
  { id: "IO", label: "Британска територия в Индийския океан" },
  { id: "BN", label: "Бруней Даруссалам" },
  { id: "BG", label: "България" },
  { id: "BF", label: "Буркина Фасо" },
  { id: "BI", label: "Бурунди" },
  { id: "CV", label: "Кабо Верде" },
  { id: "KH", label: "Камбоджа" },
  { id: "CM", label: "Камерун" },
  { id: "CA", label: "Канада" },
  { id: "KY", label: "Кайманови острови" },
  { id: "CF", label: "Централноафриканска република" },
  { id: "TD", label: "Чад" },
  { id: "CL", label: "Чили" },
  { id: "CN", label: "Китай" },
  { id: "CX", label: "Остров Кристмас" },
  { id: "CC", label: "Кокосови острови" },
  { id: "CO", label: "Колумбия" },
  { id: "KM", label: "Коморски острови" },
  { id: "CG", label: "Конго" },
  { id: "CD", label: "Конго, Демократична република" },
  { id: "CK", label: "Острови Кук" },
  { id: "CR", label: "Коста Рика" },
  { id: "CI", label: "Кот д'Ивоар" },
  { id: "HR", label: "Хърватия" },
  { id: "CU", label: "Куба" },
  { id: "CW", label: "Кюрасао" },
  { id: "CY", label: "Кипър" },
  { id: "CZ", label: "Чехия" },
  { id: "DK", label: "Дания" },
  { id: "DJ", label: "Джибути" },
  { id: "DM", label: "Доминика" },
  { id: "DO", label: "Доминиканска република" },
  { id: "EC", label: "Еквадор" },
  { id: "EG", label: "Египет" },
  { id: "SV", label: "Салвадор" },
  { id: "GQ", label: "Екваториална Гвинея" },
  { id: "ER", label: "Еритрея" },
  { id: "EE", label: "Естония" },
  { id: "SZ", label: "Есватини" },
  { id: "ET", label: "Етиопия" },
  { id: "FK", label: "Фолкландски острови" },
  { id: "FO", label: "Фарьорски острови" },
  { id: "FJ", label: "Фиджи" },
  { id: "FI", label: "Финландия" },
  { id: "FR", label: "Франция" },
  { id: "GF", label: "Френска Гвиана" },
  { id: "PF", label: "Френска Полинезия" },
  { id: "TF", label: "Френски южни територии" },
  { id: "GA", label: "Габон" },
  { id: "GM", label: "Гамбия" },
  { id: "GE", label: "Грузия" },
  { id: "DE", label: "Германия" },
  { id: "GH", label: "Гана" },
  { id: "GI", label: "Гибралтар" },
  { id: "GR", label: "Гърция" },
  { id: "GL", label: "Гренландия" },
  { id: "GD", label: "Гренада" },
  { id: "GP", label: "Гваделупа" },
  { id: "GU", label: "Гуам" },
  { id: "GT", label: "Гватемала" },
  { id: "GG", label: "Гърнси" },
  { id: "GN", label: "Гвинея" },
  { id: "GW", label: "Гвинея-Бисау" },
  { id: "GY", label: "Гвиана" },
  { id: "HT", label: "Хаити" },
  { id: "HM", label: "Остров Хърд и Острови Макдоналд" },
  { id: "VA", label: "Свети Престол (Ватикана)" },
  { id: "HN", label: "Хондурас" },
  { id: "HK", label: "Хонконг" },
  { id: "HU", label: "Унгария" },
  { id: "IS", label: "Исландия" },
  { id: "IN", label: "Индия" },
  { id: "ID", label: "Индонезия" },
  { id: "IR", label: "Иран" },
  { id: "IQ", label: "Ирак" },
  { id: "IE", label: "Ирландия" },
  { id: "IM", label: "Остров Ман" },
  { id: "IL", label: "Израел" },
  { id: "IT", label: "Италия" },
  { id: "JM", label: "Ямайка" },
  { id: "JP", label: "Япония" },
  { id: "JE", label: "Джърси" },
  { id: "JO", label: "Йордания" },
  { id: "KZ", label: "Казахстан" },
  { id: "KE", label: "Кения" },
  { id: "KI", label: "Кирибати" },
  { id: "KP", label: "Корея, Народно-демократична република" },
  { id: "KR", label: "Корея, Република" },
  { id: "KW", label: "Кувейт" },
  { id: "KG", label: "Киргизстан" },
  { id: "LA", label: "Лаос" },
  { id: "LV", label: "Латвия" },
  { id: "LB", label: "Ливан" },
  { id: "LS", label: "Лесото" },
  { id: "LR", label: "Либерия" },
  { id: "LY", label: "Либия" },
  { id: "LI", label: "Лихтенщайн" },
  { id: "LT", label: "Литва" },
  { id: "LU", label: "Люксембург" },
  { id: "MO", label: "Макао" },
  { id: "MG", label: "Мадагаскар" },
  { id: "MW", label: "Малави" },
  { id: "MY", label: "Малайзия" },
  { id: "MV", label: "Малдиви" },
  { id: "ML", label: "Мали" },
  { id: "MT", label: "Малта" },
  { id: "MH", label: "Маршалови острови" },
  { id: "MQ", label: "Мартиника" },
  { id: "MR", label: "Мавритания" },
  { id: "MU", label: "Мавриций" },
  { id: "YT", label: "Майот" },
  { id: "MX", label: "Мексико" },
  { id: "FM", label: "Микронезия" },
  { id: "MD", label: "Молдова" },
  { id: "MC", label: "Монако" },
  { id: "MN", label: "Монголия" },
  { id: "ME", label: "Черна гора" },
  { id: "MS", label: "Монсерат" },
  { id: "MA", label: "Мароко" },
  { id: "MZ", label: "Мозамбик" },
  { id: "MM", label: "Мианмар" },
  { id: "NA", label: "Намибия" },
  { id: "NR", label: "Науру" },
  { id: "NP", label: "Непал" },
  { id: "NL", label: "Нидерландия" },
  { id: "NC", label: "Нова Каледония" },
  { id: "NZ", label: "Нова Зеландия" },
  { id: "NI", label: "Никарагуа" },
  { id: "NE", label: "Нигер" },
  { id: "NG", label: "Нигерия" },
  { id: "NU", label: "Ниуе" },
  { id: "NF", label: "Остров Норфолк" },
  { id: "MK", label: "Северна Македония" },
  { id: "MP", label: "Северни Мариански острови" },
  { id: "NO", label: "Норвегия" },
  { id: "OM", label: "Оман" },
  { id: "PK", label: "Пакистан" },
  { id: "PW", label: "Палау" },
  { id: "PS", label: "Палестина" },
  { id: "PA", label: "Панама" },
  { id: "PG", label: "Папуа Нова Гвинея" },
  { id: "PY", label: "Парагвай" },
  { id: "PE", label: "Перу" },
  { id: "PH", label: "Филипини" },
  { id: "PN", label: "Острови Питкерн" },
  { id: "PL", label: "Полша" },
  { id: "PT", label: "Португалия" },
  { id: "PR", label: "Пуерто Рико" },
  { id: "QA", label: "Катар" },
  { id: "RE", label: "Реюнион" },
  { id: "RO", label: "Румъния" },
  { id: "RU", label: "Русия" },
  { id: "RW", label: "Руанда" },
  { id: "BL", label: "Сен Бартелеми" },
  { id: "SH", label: "Света Елена" },
  { id: "KN", label: "Сейнт Китс и Невис" },
  { id: "LC", label: "Сейнт Лусия" },
  { id: "MF", label: "Сен Мартен" },
  { id: "PM", label: "Сен Пиер и Микелон" },
  { id: "VC", label: "Сейнт Винсънт и Гренадини" },
  { id: "WS", label: "Самоа" },
  { id: "SM", label: "Сан Марино" },
  { id: "ST", label: "Сао Томе и Принсипи" },
  { id: "SA", label: "Саудитска Арабия" },
  { id: "SN", label: "Сенегал" },
  { id: "RS", label: "Сърбия" },
  { id: "SC", label: "Сейшели" },
  { id: "SL", label: "Сиера Леоне" },
  { id: "SG", label: "Сингапур" },
  { id: "SX", label: "Синт Мартен" },
  { id: "SK", label: "Словакия" },
  { id: "SI", label: "Словения" },
  { id: "SB", label: "Соломонови острови" },
  { id: "SO", label: "Сомалия" },
  { id: "ZA", label: "Южна Африка" },
  { id: "GS", label: "Южна Джорджия и Южни Сандвичеви острови" },
  { id: "SS", label: "Южен Судан" },
  { id: "ES", label: "Испания" },
  { id: "LK", label: "Шри Ланка" },
  { id: "SD", label: "Судан" },
  { id: "SR", label: "Суринам" },
  { id: "SJ", label: "Свалбард и Ян Майен" },
  { id: "SE", label: "Швеция" },
  { id: "CH", label: "Швейцария" },
  { id: "SY", label: "Сирия" },
  { id: "TW", label: "Тайван" },
  { id: "TJ", label: "Таджикистан" },
  { id: "TZ", label: "Танзания" },
  { id: "TH", label: "Тайланд" },
  { id: "TL", label: "Източен Тимор" },
  { id: "TG", label: "Того" },
  { id: "TK", label: "Токелау" },
  { id: "TO", label: "Тонга" },
  { id: "TT", label: "Тринидад и Тобаго" },
  { id: "TN", label: "Тунис" },
  { id: "TR", label: "Турция" },
  { id: "TM", label: "Туркменистан" },
  { id: "TC", label: "Острови Търкс и Кайкос" },
  { id: "TV", label: "Тувалу" },
  { id: "UG", label: "Уганда" },
  { id: "UA", label: "Украйна" },
  { id: "AE", label: "Обединени арабски емирства" },
  { id: "GB", label: "Обединено кралство" },
  { id: "US", label: "Съединени американски щати" },
  { id: "UM", label: "Малки далечни острови на САЩ" },
  { id: "UY", label: "Уругвай" },
  { id: "UZ", label: "Узбекистан" },
  { id: "VU", label: "Вануату" },
  { id: "VE", label: "Венецуела" },
  { id: "VN", label: "Виетнам" },
  { id: "VG", label: "Британски Вирджински острови" },
  { id: "VI", label: "Американски Вирджински острови" },
  { id: "WF", label: "Уолис и Футуна" },
  { id: "EH", label: "Западна Сахара" },
  { id: "YE", label: "Йемен" },
  { id: "ZM", label: "Замбия" },
  { id: "ZW", label: "Зимбабве" },
];

export const BANK_OPTIONS = [
  { id: "DSK", label: "БАНКА ДСК АД" },
  { id: "EUROBANK", label: "ЮРОБАНК БЪЛГАРИЯ АД" },
  { id: "INVESTBANK", label: "ИНВЕСТБАНК АД" },
  { id: "ALLIANZ", label: "АЛИАНЦ БАНК БЪЛГАРИЯ АД" },
  { id: "TBI", label: "ТИ БИ АЙ БАНК ЕАД" },
  { id: "INTERNATIONAL_ASSET", label: "ИНТЕРНЕШЪНЪЛ АСЕТ БАНК АД" },
  { id: "BULGARIAN_DEVELOPMENT", label: "БЪЛГАРСКА БАНКА ЗА РАЗВИТИЕ ЕАД" },
  { id: "UNICREDIT", label: "УНИКРЕДИТ БУЛБАНК АД" },
  { id: "UBB", label: "ОБЕДИНЕНА БЪЛГАРСКА БАНКА АД" },
  { id: "FIRST_INVESTMENT", label: "ПЪРВА ИНВЕСТИЦИОННА БАНКА АД" },
  { id: "CENTRAL_COOPERATIVE", label: "ЦЕНРТАЛНА КООПЕРАТИВНА БАНКА АД" },
  { id: "BACB", label: "БЪЛГАРО-АМЕРИКАНСКА КРЕДИТНА БАНКА АД" },
  { id: "PROCREDIT", label: "ПРОКРЕДИТ БАНК БЪЛГАРИЯ ЕАД" },
  { id: "COMMERCIAL", label: "ТЪРГОВСКА БАНКА АД" },
  { id: "TOKUDA", label: "ТОКУДА БАНК АД" },
  { id: "TEXIMBANK", label: "ТЕКСИМ БАНК АД" },
  { id: "MUNICIPAL", label: "ОБЩИНСКА БАНКА АД" },
  { id: "OTHER", label: "ДРУГА" },
];

export const DIRECTION_OPTIONS = [
  { id: "TECHNICAL_SCIENCES", label: "Технически науки" },
  { id: "NATURAL_SCIENCES", label: "Природни науки" },
  { id: "SOCIAL_SCIENCES", label: "Социални науки" },
];

export const SUBJECT_OPTIONS = [
  { id: "MATHEMATICS", label: "Математика" },
  { id: "PHYSICS", label: "Физика" },
  { id: "CHEMISTRY", label: "Химия" },
  { id: "BIOLOGY", label: "Биология" },
  { id: "HISTORY", label: "История" },
  { id: "GEOGRAPHY", label: "География" },
  { id: "FOREIGN_LANGUAGE", label: "Чужд език" },
];

export const DEGREE_LEVELS = [
  { id: "BACHELOR", label: "Бакалавър" },
  { id: "MASTER", label: "Магистър" },
  { id: "DOCTORAL", label: "Докторант" },
];

export const COURSE_YEARS = [
  { id: "FIRST", label: "Първи" },
  { id: "SECOND", label: "Втори" },
  { id: "THIRD", label: "Трети" },
  { id: "FOURTH", label: "Четвърти" },
];

export const SEMESTERS = [
  { id: "WINTER", label: "Зимен" },
  { id: "SUMMER", label: "Летен" },
];

export const FAMILY_STATUSES = [
  { id: "MARRIED", label: "Семейни" },
  { id: "SINGLE", label: "Несемейни" },
];

export const SCHOLARSHIP_OPTIONS = [
  {
    id: "MERIT_SUCCESS",
    label: "Стипендия за успех (успех от 5.00 до 6.00)",
  },
  {
    id: "MERIT_WITH_INCOME",
    label: "Стипендия за успех с доходи (успех от 4.00 до 4.99)",
  },
  {
    id: "SOCIAL_PREFERENTIAL",
    label: "Стипендия (социална/предимствена)",
  },
  {
    id: "FOREIGN_STUDENT",
    label: "Стипендия за чуждестранни студенти",
  },
  {
    id: "FIRST_YEAR",
    label: "Стипендия ПЪРВОКУРСНИК",
  },
  {
    id: "SPECIAL_ACHIEVEMENTS",
    label: "Стипендия за специални постижения",
  },
];

export const SOCIAL_TYPES = [
  {
    id: "DISABLED_STUDENT",
    label: "Студент с трайни увреждания",
  },
  {
    id: "ORPHAN_STUDENT",
    label: "Несемеен студент без двама родители",
  },
  {
    id: "ONE_PARENT_DECEASED_ONE_DISABLED",
    label: "Несемеен студент с починал родител и родител, който е с трайни увреждания",
  },
  {
    id: "BOTH_PARENTS_DISABLED",
    label: "Студент с двама родители с трайни увреждания",
  },
  {
    id: "PARENT_WITH_CHILD_UNDER_6",
    label: "Майки/Бащи на деца до 6 год. възраст",
  },
  {
    id: "CHILD_PROTECTION_MEASURE",
    label: "Студент, който до пълнолетие са с предприета мярка за закрила по реда на ЗЗД",
  },
];

// Add more dropdown options as needed

/**
 * Helper functions to get display values from IDs
 */
export const getDisplayValue = (optionsArray, id) => {
  if (!id) return "—";
  const found = optionsArray.find((item) => item.id === id);
  return found ? found.label : id;
};

export const getBankName = (id) => getDisplayValue(BANK_OPTIONS, id);
export const getDirectionName = (id) => getDisplayValue(DIRECTION_OPTIONS, id);
export const getSubjectName = (id) => getDisplayValue(SUBJECT_OPTIONS, id);
export const getDegreeLevelName = (id) => getDisplayValue(DEGREE_LEVELS, id);
export const getCourseYearName = (id) => getDisplayValue(COURSE_YEARS, id);
export const getSemesterName = (id) => getDisplayValue(SEMESTERS, id);
export const getFamilyStatusName = (id) => getDisplayValue(FAMILY_STATUSES, id);
export const getScholarshipName = (id) => getDisplayValue(SCHOLARSHIP_OPTIONS, id);
export const getSocialTypeName = (id) => getDisplayValue(SOCIAL_TYPES, id);
export const getCountryName = (id) => getDisplayValue(COUNTRY_CODES, id);
